import type { Metadata } from 'next';

import './globals.css';

import './globals.css';

// import DrawerComponent from '@/components/custom/Drawer';
import dynamic from 'next/dynamic';

export const metadata: Metadata = {
    title: '태풍마켓',
    description: 'Generated by create next app',
};

<<<<<<< Updated upstream
export default function RootLayout(props: React.PropsWithChildren) {
    return (
        <html lang="en">
            <body>{props.children}</body>
        </html>
=======
const DrawerComponentWithNoSSR = dynamic(() => import('@/components/custom/Drawer'), { ssr: false });

const PortalWithNoSSR = dynamic(() => import('@/components/custom/MordalPortal'), { ssr: false });

export default function RootLayout(props: React.PropsWithChildren) {
    return (
        <StoreProvider>
            <html lang="en">
                <body>
                    {/* <Header /> */}
                    <div id="modal-root" />
                    <PortalWithNoSSR>
                        <DrawerComponentWithNoSSR />
                    </PortalWithNoSSR>
                    {props.children}
                    <div id="portal"></div>
                </body>
                {/* <script type="text/javascript" src="https://cdn.iamport.kr/js/iamport.payment-1.1.8.js"></script> */}
            </html>
        </StoreProvider>
>>>>>>> Stashed changes
    );
}
