import type { Metadata } from 'next';

import './globals.css';

import StoreProvider from './StoreProvider';

export const metadata: Metadata = {
    title: '태풍마켓',
    description: 'Generated by create next app',
};

export default function RootLayout(props: React.PropsWithChildren) {
    return (
        <StoreProvider>
            <html lang="en">
                <body>
                    {/* <Header /> */}
                    {props.children}
                    <div id="portal"></div>
                </body>
            </html>
        </StoreProvider>
    );
}
