import type { Metadata } from 'next';
import './globals.css';
import Drawer from '@/components/custom/Drawer';
import StoreProvider from './StoreProvider';
// import DrawerComponent from '@/components/custom/Drawer';
import dynamic from 'next/dynamic';
import Portal from '@/components/custom/MordalPortal';

import StoreProvider from './StoreProvider';

export const metadata: Metadata = {
    title: '태풍마켓',
    description: 'Generated by create next app',
};

const DrawerComponentWithNoSSR = dynamic(
    () => import('@/components/custom/Drawer'),
    { ssr: false }
);

const PortalWithNoSSR = dynamic(
    () => import('@/components/custom/MordalPortal'),
    { ssr: false }
);


export default function RootLayout(props: React.PropsWithChildren) {
    return (
        <StoreProvider>
            <html lang="en">
                <body>
                    {/* <Header /> */}
                    {props.children}
                    <div id="portal"></div>
                    <div id='modal-root' />
                    <PortalWithNoSSR>
                        <DrawerComponentWithNoSSR />
                    </PortalWithNoSSR>
                    {props.children}
                </body>
               {/* <script type="text/javascript" src="https://cdn.iamport.kr/js/iamport.payment-1.1.8.js"></script> */}
            </html>
        </StoreProvider>
    );
}
